trigger: none

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: TerraformInstaller@1
    displayName: Install Terraform 1.3.9
    inputs:
      terraformVersion: 1.4.0
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: 'terraform-demo'
      backendServiceArm: 'mysvc'
      backendAzureRmResourceGroupName: 'test-demo'
      backendAzureRmStorageAccountName: 'mysa89'
      backendAzureRmContainerName: 'mycontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: 'terraform-demo'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: 'terraform-demo'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: 'terraform-demo'
      commandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'mysvc'